/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author SHILPI
 */
public class ManageStudents extends javax.swing.JFrame {

    /**
     * Creates new form ManageBooks
     */
    public ManageStudents() {
        initComponents();
        setDataToTable();
    }
    DefaultTableModel model;
public void setDataToTable(){
    try{
        Connection con=DBConnection.getConnection();
        Statement pst=con.createStatement();
        ResultSet result=pst.executeQuery("select * from student_details");
        while(result.next()){
            int studentId=result.getInt("student_id");
            String studentName=result.getString("student_name");
            String  course=result.getString("course");
            String branch=result.getString("branch");
            
            Object[] obj={studentId,studentName,course,branch};
            model =(DefaultTableModel) table_studentDetails.getModel();
            model.addRow(obj);
        }
}
    catch(Exception e){
        e.printStackTrace();
    }
}
//to add student
 public boolean addStudent(){
        int student_id=Integer.parseInt(text_studentId.getText());
        String student_name=text_StudentName.getText();
        String course=text_course.getSelectedItem().toString();
        String branch=text_branch.getSelectedItem().toString();
        
        boolean gotAdded=false;
        
        try{
            Connection con=DBConnection.getConnection();
            String sql="insert into student_details values(?,?,?,?)";
            PreparedStatement pt=con.prepareStatement(sql);
            pt.setInt(1,student_id);
            pt.setString(2,student_name);
            pt.setString(3,course);
            pt.setString(4,branch);
            int rowcount=pt.executeUpdate();
            if(rowcount>0){
                gotAdded=true;
//              JOptionPane.showMessageDialog(this,"New Book Added Successfully");
            }
            else{
                gotAdded=false;
//                JOptionPane.showMessageDialog(this,"Failed,Try Adding it again");
            }
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return gotAdded;
    }
  //method to clear table
 public void clearTable(){
     model=(DefaultTableModel)table_studentDetails.getModel();
     model.setRowCount(0);
     
     
 }
 //to  delete student details
 public boolean deleteStudent(){
     boolean isDeleted=false;
     int student_id=Integer.parseInt(text_studentId.getText());
     try{
        Connection con=DBConnection.getConnection();
        String sql="delete from student_details where student_id=?";
        PreparedStatement ps=con.prepareStatement(sql);
        ps.setInt(1,student_id);
        int rowcount=ps.executeUpdate();
         if(rowcount>0){
             isDeleted=true;
         }
         else{
             isDeleted=false;
         }
     }
     catch(Exception e){
         e.printStackTrace();
     }
     return isDeleted;
 }
 //to update student details
 public boolean updateStudentDetails(){
        int student_id=Integer.parseInt(text_studentId.getText());
        String student_name=text_StudentName.getText();
        String course=text_course.getSelectedItem().toString();
        String branch=text_branch.getSelectedItem().toString();
        
        boolean isUpdated=false;
        
        try{
            Connection con=DBConnection.getConnection();
            String sql="update student_details set student_name=?,course=?,branch=? where student_id=?";
//           String sql="update book_details values(?,?,?,?)"; 
            PreparedStatement pt=con.prepareStatement(sql);
            pt.setString(1,student_name);
            pt.setString(2,course);
            pt.setString(3,branch);
            pt.setInt(4,student_id);
            int rowcount=pt.executeUpdate();
            if(rowcount>0){
                isUpdated=true;
//              JOptionPane.showMessageDialog(this,"New Book Added Successfully");
            }
            else{
                isUpdated=false;
//                JOptionPane.showMessageDialog(this,"Failed,Try Adding it again");
            }
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return isUpdated;
 } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        text_studentId = new javax.swing.JTextField();
        text_StudentName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        text_branch = new javax.swing.JComboBox<>();
        text_course = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_studentDetails = new rojerusan.RSTableMetro();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 51, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel4.setText("Back");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter Student Id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Moleskine_26px.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 40, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Enter Student Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 140, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Moleskine_26px.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Select Course");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 120, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Collaborator_Male_26px.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Select Branch");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 120, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Unit_26px.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));
        jPanel1.add(text_studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 260, 40));
        jPanel1.add(text_StudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 260, 40));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 670, 100, 30));

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 620, 100, 30));

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 100, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Book Details Form");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 210, 50));

        text_branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CS", "IT", "PLAIN", "MEC", "CHEM", "CIVIL", "ELE", "MME", "ECE", " " }));
        text_branch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_branchActionPerformed(evt);
            }
        });
        jPanel1.add(text_branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 260, 40));

        text_course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.tech", "M.tech", "PHD", "BSC", "MSC", "BCA", "MCA" }));
        text_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_courseActionPerformed(evt);
            }
        });
        jPanel1.add(text_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 260, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 810));

        jPanel5.setBackground(new java.awt.Color(253, 217, 131));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/libbg.jpg"))); // NOI18N
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 640, 570, 180));

        jLabel2.setFont(new java.awt.Font("Pristina", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Student_Male_100px.png"))); // NOI18N
        jLabel2.setText("Manage Students");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 390, 100));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 20, 30));

        table_studentDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "Student Name", "Course", "Branch"
            }
        ));
        table_studentDetails.setColorBackgoundHead(new java.awt.Color(255, 51, 0));
        table_studentDetails.setColorFilasBackgound1(new java.awt.Color(255, 204, 0));
        table_studentDetails.setColorFilasForeground1(new java.awt.Color(204, 0, 0));
        table_studentDetails.setColorFilasForeground2(new java.awt.Color(204, 0, 0));
        table_studentDetails.setColorSelBackgound(new java.awt.Color(204, 0, 0));
        table_studentDetails.setRowHeight(40);
        table_studentDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_studentDetailsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table_studentDetails);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 780, 320));

        jLabel6.setBackground(new java.awt.Color(255, 255, 153));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/libbg.jpg"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, -1, 180));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 1060, 810));

        setSize(new java.awt.Dimension(1500, 810));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Home home =new Home();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void table_studentDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_studentDetailsMouseClicked
        int rowNo=table_studentDetails.getSelectedRow();
        TableModel model= table_studentDetails.getModel();
        
        text_studentId.setText(model.getValueAt(rowNo, 0).toString());
        text_StudentName.setText(model.getValueAt(rowNo, 1).toString());
        text_course.setSelectedItem(model.getValueAt(rowNo, 2).toString());
        text_branch.setSelectedItem(model.getValueAt(rowNo, 3).toString());
        
    }//GEN-LAST:event_table_studentDetailsMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(addStudent()==true){
           JOptionPane.showMessageDialog(this,"Student Added");
           clearTable();
           setDataToTable();
       }
       else{
           JOptionPane.showMessageDialog(this,"Failed, Try Adding Again");
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(updateStudentDetails()==true){
           JOptionPane.showMessageDialog(this,"Student Details Updated");
           clearTable();
           setDataToTable();
       }
       else{
           JOptionPane.showMessageDialog(this,"Failed, Try Updating Again");
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(deleteStudent()==true){
           JOptionPane.showMessageDialog(this,"Student Details Deleted Successfully");
           clearTable();
           setDataToTable();
       }
       else{
           JOptionPane.showMessageDialog(this,"Failed, Try Deleting Again");
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void text_branchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_branchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_branchActionPerformed

    private void text_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_courseActionPerformed
// to add books into table
//    int book_id,quantity;
//    String book_name,author;
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private rojerusan.RSTableMetro table_studentDetails;
    private javax.swing.JTextField text_StudentName;
    private javax.swing.JComboBox<String> text_branch;
    private javax.swing.JComboBox<String> text_course;
    private javax.swing.JTextField text_studentId;
    // End of variables declaration//GEN-END:variables
}
